MODEL:
  NAME: resnet50
LOSS:
  CLA_LOSS: arcface
  CLA_S: 16.
  CLA_M: 0.1
  PAIR_LOSS: triplet
  PAIR_M: 0.3
DATA:
  TRAIN_BATCH: 256  
  TEST_BATCH: 256   
TRAIN:
  MAX_EPOCH: 100    
TAG: res50-arcface-triplet