MODEL:
  NAME: resnet50
LOSS:
  CLA_LOSS: crossentropylabelsmooth
  PAIR_LOSS: triplet
  PAIR_M: 0.3
DATA:
  TRAIN_BATCH: 256  
  TEST_BATCH: 256   
TRAIN:
  MAX_EPOCH: 100    
TAG: res50-celabelsmooth-triplet